In [8]:
#DATA for IL37
import json
import numpy as np

# Define binder length and file path

file_path = r"C:\Users\henry\OneDrive - Emory\Rafiq lab\R.LAB Fall 2025\ipae\AlphaFold Outputs\18R1-1R8(Full)-IL37\fold_2025_10_07_il_18r1_bound_il_18r_bound_il37wt_full_data_0.json"

with open(file_path, "r") as f:
    data1 = json.load(f)
# Load JSON file
pae1 = np.array(data1["pae"])
print(pae1)
# Assume these are your lengths (from token_chain_ids or sequence)
chain_lengths = [522, 478, 173]  # A, B, C
chain_labels = ['A', 'B', 'C']   # Consistent with token_chain_ids
chain_roles = ['receptor', 'dimer', 'receptor']

# Compute boundaries
chain_boundaries = []
start = 0
for length in chain_lengths:
    chain_boundaries.append((start, start + length))
    start += length

# Collect only dimer <> receptor interactions
interface_pae_values = []

for i in range(len(chain_labels)):
    for j in range(i+1, len(chain_labels)):
        if i == j:
            continue  # skip intra-chain
        if chain_roles[i] == 'receptor' and chain_roles[j] == 'receptor':
            continue  # skip receptor–receptor interaction

        start_i, end_i = chain_boundaries[i]
        start_j, end_j = chain_boundaries[j]

        upper = pae1[start_i:end_i, start_j:end_j].reshape(-1)
        lower = pae1[start_j:end_j, start_i:end_i].reshape(-1)

        interface_pae_values.extend(upper)
        interface_pae_values.extend(lower)

# Final cumulative mean
pae_i = np.mean(interface_pae_values)
print(f"Filtered interface PAE (dimer-receptor only): {pae_i:.2f}")

[[ 0.8  3.8  6.6 ... 30.8 30.9 30.7]
 [ 2.   0.8  2.4 ... 30.5 30.5 30.4]
 [ 3.9  1.7  0.8 ... 30.3 30.2 30.2]
 ...
 [31.1 30.8 30.7 ...  0.8  3.5  5.6]
 [31.2 31.1 31.  ...  2.5  0.8  3.2]
 [31.2 31.1 31.  ...  5.6  3.1  0.8]]
Filtered interface PAE (dimer-receptor only): 29.08


In [9]:
#N_peptides
import numpy as np

# Example PAE matrix for 3 chains with lengths [430, 430, 518]

file_path = r"C:\Users\henry\OneDrive - Emory\Rafiq lab\R.LAB Fall 2025\ipae\AlphaFold Outputs\18R1-1R8(Full)-IL37\fold_2025_10_07_il_18r1_bound_il_18r_bound_il37wt_full_data_0.json"

with open(file_path, "r") as f:
    data1 = json.load(f)
# Load JSON file
pae1 = np.array(data1["pae"])
print(pae1)
# Assume these are your lengths (from token_chain_ids or sequence)
chain_lengths = [522, 478, 173]  # A, B, C
total_length = sum(chain_lengths)
# Input the PAE matrix for testing (values 0–30 Å)


# Compute chain boundaries
chain_boundaries = []
start = 0
for L in chain_lengths:
    chain_boundaries.append((start, start + L))
    start += L

# Collect all inter-chain PAE blocks
all_interface_values = []

for i in range(len(chain_boundaries)):
    for j in range(i+1, len(chain_boundaries)):
        if i == j:
            continue  # skip intra-chain

        start_i, end_i = chain_boundaries[i]
        start_j, end_j = chain_boundaries[j]

        # Extract and flatten both directions: i->j and j->i
        upper = pae1[start_i:end_i, start_j:end_j].reshape(-1)
        lower = pae1[start_j:end_j, start_i:end_i].reshape(-1)

        all_interface_values.extend(upper)
        all_interface_values.extend(lower)

# Compute the mean of all inter-chain PAE values
pae_i = np.mean(all_interface_values)
print(f"Cumulative interface PAE (pae_i) across {len(chain_lengths)} chains: {pae_i:.2f}")

[[ 0.8  3.8  6.6 ... 30.8 30.9 30.7]
 [ 2.   0.8  2.4 ... 30.5 30.5 30.4]
 [ 3.9  1.7  0.8 ... 30.3 30.2 30.2]
 ...
 [31.1 30.8 30.7 ...  0.8  3.5  5.6]
 [31.2 31.1 31.  ...  2.5  0.8  3.2]
 [31.2 31.1 31.  ...  5.6  3.1  0.8]]
Cumulative interface PAE (pae_i) across 3 chains: 29.21


In [10]:
#N_peptides
import numpy as np

# Example PAE matrix for 3 chains with lengths [430, 430, 518]

file_path = r"C:\Users\henry\OneDrive - Emory\Rafiq lab\R.LAB Fall 2025\ipae\AlphaFold Outputs\18R1-1R8(Full)-IL37\fold_2025_10_07_il_18r1_bound_il_18r_bound_il37d73k_full_data_0.json"

with open(file_path, "r") as f:
    data1 = json.load(f)
# Load JSON file
pae1 = np.array(data1["pae"])
print(pae1)
# Assume these are your lengths (from token_chain_ids or sequence)
chain_lengths = [522, 478, 173]  # A, B, C
total_length = sum(chain_lengths)
# Input the PAE matrix for testing (values 0–30 Å)


# Compute chain boundaries
chain_boundaries = []
start = 0
for L in chain_lengths:
    chain_boundaries.append((start, start + L))
    start += L

# Collect all inter-chain PAE blocks
all_interface_values = []

for i in range(len(chain_boundaries)):
    for j in range(i+1, len(chain_boundaries)):
        if i == j:
            continue  # skip intra-chain

        start_i, end_i = chain_boundaries[i]
        start_j, end_j = chain_boundaries[j]

        # Extract and flatten both directions: i->j and j->i
        upper = pae1[start_i:end_i, start_j:end_j].reshape(-1)
        lower = pae1[start_j:end_j, start_i:end_i].reshape(-1)

        all_interface_values.extend(upper)
        all_interface_values.extend(lower)

# Compute the mean of all inter-chain PAE values
pae_i = np.mean(all_interface_values)
print(f"Cumulative interface PAE (pae_i) across {len(chain_lengths)} chains: {pae_i:.2f}")

[[ 0.8  3.3  5.8 ... 30.6 30.8 30.8]
 [ 1.8  0.8  2.2 ... 30.3 30.3 30.4]
 [ 3.7  1.6  0.8 ... 30.  29.9 29.9]
 ...
 [31.2 30.8 30.7 ...  0.8  3.5  5.5]
 [31.3 31.  31.  ...  2.5  0.8  3.1]
 [31.3 31.1 31.1 ...  5.4  3.   0.8]]
Cumulative interface PAE (pae_i) across 3 chains: 28.68
